client_config_backend: settings
client_config:
  client_id: GENERE UN ID CLIENTE MEDIANTE AUTENTICACION GOOGLE
  client_secret: GENERE UN CLIENTE SECRETO MEDIANTE AUTENTICACION GOOGLE

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials_module.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive
